# Generated by Django 3.0.8 on 2020-07-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_userdetail_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
    ]
