# Generated by Django 3.0.8 on 2020-07-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_userdetail_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='movie_title',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_poster',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
