# Generated by Django 3.0.8 on 2020-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200729_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
