# Generated by Django 3.0.8 on 2020-07-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200729_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_poster',
            new_name='Poster',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_year',
            new_name='Year',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_id',
            new_name='imdbID',
        ),
    ]
